name: PulseOps CI/CD

on:
  push:
    branches:
      - develop   # CI/CD triggers on develop branch
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3Ô∏è‚É£ Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4Ô∏è‚É£ Make scripts executable
      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      # 5Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: ./scripts/build.sh
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      # 6Ô∏è‚É£ Push Docker image
      - name: Push Docker image
        run: ./scripts/push.sh
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_PUSH: ${{ secrets.DOCKER_PUSH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1Ô∏è‚É£ Checkout code (optional if you need local docker-compose)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ SSH & deploy on server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/pulseops
            docker exec pulseops-app node src/seeds/scheduled-jobs.seed.js

            echo "‚è≥ Pulling latest image..."
            docker-compose pull

            echo "üöÄ Restarting containers..."
            docker-compose up -d

            echo "‚úÖ Deployment complete"
